apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: giy83efl9-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-7d3db61d12.2u21.p3.openshiftapps.com/rhtap/rhtap-qe:d07fcc5da2dfdc3ac3b9babc1d84d181a301f903@sha256:45a243a9e2dbf1443a132fbaebc2297e243a804bab10f8fb3187a220b94326ad
        name: container-image  
